config/routes.rb
Paloalto::Application.routes.draw do

  root 'answers#new'

  resources :answers do 
    collection do 
      get 'agreement'
      get 'avr'
    end
  end

  get "survey/customer" => "answers#new"

  get "admins/index" => "admins#index"
  get "admins/index/question" => "admins#index_question"
  get "mail" => "answers#dummy"
  get "admins/index/question/:qid/:aid" => "admins#show_question_detail"

  get "admin" => "admins#sign_in"
  post "admins/authorize" => "admins#authorize"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  paginates_per 50
end

app/controllers/admins_controller.rb
#encoding: utf-8
class AdminsController < ApplicationController
  before_filter :set_questions_and_answers
  before_filter :auth_check, :except => [:sign_in, :authorize]
  layout 'bootstrap', :except => :index
  layout 'admins', :only => :index

  def auth_check
    if session[:admin] == nil
      flash[:error] = "로그인 해 주세요."
      redirect_to "/admin"
    end
  end

  def sign_in

  end

  def authorize
    if params[:id] == "admin" and params[:password] == "jkl"
      session[:admin] = "admin"
      redirect_to "/admins/index"
    else
      flash[:error] = "아이디 혹은 비밀번호가 일치하지 않습니다."
      redirect_to "/admin"
    end
  end

  def index
    @answers = Answer.all.page params[:page]
    respond_to do |format|
      format.html
      format.xls {
        @total_num = Answer.count
        @analysis = []
        @analysis_1 = []
        @analysis_1 << Answer.where(:answer_1 => 1).count
        @analysis_1 << Answer.where(:answer_1 => 2).count
        @analysis_1 << Answer.where(:answer_1 => 3).count
        @analysis_1 << Answer.where(:answer_1 => 4).count
        @analysis_1 << Answer.where(:answer_1 => 5).count
        @analysis_2 = []
        @analysis_2 << Answer.where(:answer_2 => 1).count
        @analysis_2 << Answer.where(:answer_2 => 2).count
        @analysis_3 = []
        @analysis_3 << Answer.where(:answer_3 => 1).count
        @analysis_3 << Answer.where(:answer_3 => 2).count
        @analysis_3 << Answer.where(:answer_3 => 3).count
        @analysis_3 << Answer.where(:answer_3 => 4).count
        @analysis_4 = []
        @analysis_4 << Answer.where(:answer_4 => 1).count
        @analysis_4 << Answer.where(:answer_4 => 2).count
        @analysis_5 = []
        @analysis_5 << Answer.where(:answer_5 => 1).count
        @analysis_5 << Answer.where(:answer_5 => 2).count
        @analysis_6 = []
        @analysis_6 << Answer.where(:answer_6 => 1).count
        @analysis_6 << Answer.where(:answer_6 => 2).count
        @analysis << @analysis_1
        @analysis << @analysis_2
        @analysis << @analysis_3
        @analysis << @analysis_4
        @analysis << @analysis_5
        @analysis << @analysis_6
        @idx = -1
        Axlsx::Package.new do |p|
          p.workbook.add_worksheet(:name => "전체보기") do |sheet|
            sheet.add_row ["회사명", "담당자", "부서명", "사무실 전화", "직책", "이메일", "휴대폰", @questions[0], @questions[1], @questions[2], @questions[3], @questions[4], @questions[5]]
            Answer.all.each do |ans|
              sheet.add_row [ans.company_name, ans.manager_name, ans.department, ans.phone, ans.work_level, ans.email, ans.cellphone, @answer[0][ans.answer_1], @answer[1][ans.answer_2], @answer[2][ans.answer_3],@answer[3][ans.answer_4],@answer[4][ans.answer_5],@answer[5][ans.answer_6] ]
            end
          end
          p.workbook.add_worksheet(:name => "질문으로 모아보기") do |sheet|
            sheet.add_row ["no", "질문", "답변 통계"]
            @questions.each do |q|
              @idx += 1
              0..@analysis[@idx].length.times do |i|
                if i == 0
                  sheet.add_row [ @idx + 1, q, @answer[@idx][i+1], @analysis[@idx][i], (@analysis[@idx][i].to_f * 100.0 / @total_num.to_f).round(2).to_s + " %"]
                else
                  sheet.add_row [ nil, nil, @answer[@idx][i+1], @analysis[@idx][i], (@analysis[@idx][i].to_f * 100.0 / @total_num.to_f).round(2).to_s + " %"]
                end
              end
            end
          end
          temp = Tempfile.new('test.xlsx')
          p.serialize(temp.path)
          send_file temp.path, :filename => "jkl.xlsx", :type => "application/xlsx"
        end
      }
    end
  end

  def index_question
    @total_num = Answer.count
    @analysis = []
    @analysis_1 = []
    @analysis_1 << Answer.where(:answer_1 => 1).count
    @analysis_1 << Answer.where(:answer_1 => 2).count
    @analysis_1 << Answer.where(:answer_1 => 3).count
    @analysis_1 << Answer.where(:answer_1 => 4).count
    @analysis_1 << Answer.where(:answer_1 => 5).count
    @analysis_2 = []
    @analysis_2 << Answer.where(:answer_2 => 1).count
    @analysis_2 << Answer.where(:answer_2 => 2).count
    @analysis_3 = []
    @analysis_3 << Answer.where(:answer_3 => 1).count
    @analysis_3 << Answer.where(:answer_3 => 2).count
    @analysis_3 << Answer.where(:answer_3 => 3).count
    @analysis_3 << Answer.where(:answer_3 => 4).count
    @analysis_4 = []
    @analysis_4 << Answer.where(:answer_4 => 1).count
    @analysis_4 << Answer.where(:answer_4 => 2).count
    @analysis_5 = []
    @analysis_5 << Answer.where(:answer_5 => 1).count
    @analysis_5 << Answer.where(:answer_5 => 2).count
    @analysis_6 = []
    @analysis_6 << Answer.where(:answer_6 => 1).count
    @analysis_6 << Answer.where(:answer_6 => 2).count
    @analysis << @analysis_1
    @analysis << @analysis_2
    @analysis << @analysis_3
    @analysis << @analysis_4
    @analysis << @analysis_5
    @analysis << @analysis_6
  end

  def show_question_detail
    answer = "answer_" + params[:qid]
    @answers = Answer.where("#{answer} = #{params[:aid]}")
    render :layout => 'fixed'
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    
  end

  def new
    @answer = Answer.new
  end

  def new2
    @answer = Answer.new
  end

  def create
    Rails.logger.info(params[:answer])
    @answer = Answer.new
    @answer.company_name = params[:answer][:company_name]
    @answer.manager_name = params[:answer][:manager_name]
    @answer.phone = params[:answer][:phone]
    @answer.work_level = params[:answer][:work_level]
    @answer.email = params[:answer][:email]
    @answer.cellphone = params[:answer][:cellphone]
    @answer.department = params[:answer][:department]
    @answer.answer_1 = params[:answer][:answer_1].to_i
    @answer.answer_2 = params[:answer][:answer_2].to_i
    @answer.answer_3 = params[:answer][:answer_3].to_i
    @answer.answer_4 = params[:answer][:answer_4].to_i
    @answer.answer_5 = params[:answer][:answer_5].to_i
    @answer.answer_6 = params[:answer][:answer_6].to_i
    
    if @answer.save
      Rails.logger.info("save success!")
      rlt = {}
      rlt[:success] = true
      render :json => rlt.to_json
    else
      Rails.logger.info("save fail!")
      render :action => "new"
    end
  end

  def edit

  end

  def update

  end

  def show
    @answer = Answer.find(params[:id])
  end

  def destroy

  end

  def agreement
    render :layout => false
  end

  def avr
    render :layout => false
  end

  def dummy
    render :layout => false
  end
end

app/controllers/application_controller.rb
#encoding: utf-8
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def set_questions_and_answers
    @questions = []
    @questions << "현재 사용 중인 데스크톱/노트북 대수는 어떻게 되십니까?"
    @questions << "차세대 방화벽에 대해서 알고 계시거나 소개를 받으신 적이 있습니까?"
    @questions << "현재 사용하고 계시는 방화벽에 대한 불만사항이 있다면 어떤 것이 있습니까?"
    @questions << "차세대 방화벽 구축 프로젝트에 대해서 방문컨설팅을 원하십니까?"
    @questions << "팔로알토 네트웍스 솔루션에 관한 제품정보, 신제품 출시, 세미나 초청 등 마케팅 관련 자료를 수신하겠습니까?"
    @questions << "팔로알토 네트웍스의 AVR(Application Visibility and Risk Report) 프로그램을 통해 귀사의 네트워크에 대한 건강 진단을 원하십니까?"

    @answer = []
    answer = []
    answer << ""
    answer << "100대 미만"
    answer << "100대 이상~1,000대 미만"
    answer << "1,000대 이상~5,000대 미만"
    answer << "5,000대 이상~10,000대 미만"
    answer << "10,000대 이상"
    @answer << answer
    answer = []
    answer << ""
    answer << "예"
    answer << "아니오"
    @answer << answer
    answer = []
    answer << ""
    answer << "성능이슈"
    answer << "관리 편의성 부족"
    answer << "보안기능 미비"
    answer << "없음"
    @answer << answer
    answer = []
    answer << ""
    answer << "예"
    answer << "아니오"
    @answer << answer
    answer = []
    answer << ""
    answer << "예"
    answer << "아니오"
    @answer << answer
    answer = []
    answer << ""
    answer << "예"
    answer << "아니오"
    @answer <<  answer
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/index.html.erb
<div container="admin_index_container">
  <table class="table table-striped table-hover table-condensed admin_index">
    <colgroup>
      <col width="120px;">
      <col width="120px;">
      <col width="120px;">
      <col width="120px;">
      <col width="100px;">
      <col width="200px;">
      <col width="140px;">
      <col width="400px;">
      <col width="500px;">
      <col width="550px;">
      <col width="500px;">
      <col width="500px;">
      <col width="500px;">
    </colgroup>
    <thead>
    <tr class="row">
      <th colspan="6">Information</th>
      <th>Q1</th>
      <th>Q2</th>
      <th>Q3</th>
      <th>Q4</th>
      <th>Q5</th>
      <th>Q6</th>
    </tr>
    <tr>
      <th>회사명</th>
      <th>담당자</th>
      <th>부서명</th>
      <th>사무실 전화</th>
      <th>직책</th>
      <th>이메일</th>
      <th>휴대폰</th>
      <th><%= @questions[0] %></th>
      <th><%= @questions[1] %></th>
      <th><%= @questions[2] %></th>
      <th><%= @questions[3] %></th>
      <th><%= @questions[4] %></th>
      <th><%= @questions[5] %></th>
    </tr>
    </thead>
    <tbody class="">
      <% @answers.each do |ans| %>
        <tr>
          <td><%= ans.company_name %></td>
          <td><%= ans.manager_name %></td>
          <td><%= ans.department %></td>
          <td><%= ans.phone %></td>
          <td><%= ans.work_level %></td>
          <td><%= ans.email %></td>
          <td><%= ans.cellphone %></td>
          <td><%= @answer[0][ans.answer_1] %></td>
          <td><%= @answer[1][ans.answer_2] %></td>
          <td><%= @answer[2][ans.answer_3] %></td>
          <td><%= @answer[3][ans.answer_4] %></td>
          <td><%= @answer[4][ans.answer_5] %></td>
          <td><%= @answer[5][ans.answer_6] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @answers %>
</div>

app/views/admins/index_question.html.erb
<div container="admin_main_container">
  <table class="table table-hover">
    <colgroup>
      <col width="30px;">
      <col>
      <col width="200px;">
      <col width="20px;">
      <col width="90px;">
      <col width="120px;">
    </colgroup>
    <thead>
    <tr>
      <th>no</th>
      <th>질문</th>
      <th colspan="4">답변 통계</th>
    </tr>
    </thead>
    <tbody class="table-hover">
      <% @idx = 0 %>
      <% @questions.each do |q| %>
        <tr>
          <td rowspan="<%= @analysis[@idx].length + 1 %>"><%= @idx + 1 %></td>
          <td rowspan="<%= @analysis[@idx].length + 1 %>"><%= q %></td>
          <% 0..@analysis[@idx].length.times do |i|  %>
            <tr>
              <td><%= @answer[@idx][i+1] %></td>
              <td><%= @analysis[@idx][i] %></td>
              <td><%= (@analysis[@idx][i].to_f * 100.0 / @total_num.to_f).round(2) %> %</td>
              <td><button class="btn_show_detail" data-qidx="<%= @idx + 1 %>" data-aidx="<%= i + 1 %>">자세히 보기</button></td>
            </tr>
          <% end %>
        </tr>
        <% @idx = @idx + 1 %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admins/show_question_detail.html.erb
<div container="admin_main_container">
  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th>no</th>
      <th>회사명</th>
      <th>담당자</th>
      <th>부서명</th>
      <th>사무실 전화</th>
      <th>직책</th>
      <th>이메일</th>
      <th>휴대폰</th>
    </tr>
    </thead>
    <tbody>
      <% @answers.each_with_index do |ans, i| %>
        <tr>
          <td><%= i + 1 %></td>
          <td><%= ans.company_name %></td>
          <td><%= ans.manager_name %></td>
          <td><%= ans.department %></td>
          <td><%= ans.phone %></td>
          <td><%= ans.work_level %></td>
          <td><%= ans.email %></td>
          <td><%= ans.cellphone %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admins/sign_in.html.erb
<%= form_tag("/admins/authorize", method: "post") do %>
  id: <%= text_field_tag(:id) %>
  password: <%= password_field_tag (:password) %>
  <%= submit_tag("Login") %>
<% end %>

app/views/answers/agreement.html.erb
<%= image_tag "pop_agreement.JPG" %>

app/views/answers/avr.html.erb
<%= image_tag "avr.JPG" %>

app/views/answers/new.html.erb
<div id="main_container">
  <%= form_for @answer, :url => answers_path, :remote => true do |f| %>
      <%= f.text_field :company_name, :class => "form_1" %>
      <%= f.text_field :manager_name, :class => "form_2" %>
      <%= f.text_field :department, :class => "form_3" %>
      <%= f.text_field :phone, :placeholder => "02-000-0000", :class => "form_2" %>
      <%= f.text_field :work_level, :class => "form_3" %>
      <%= f.text_field :email, :placeholder => "sample@gmail.com", :class => "form_2" %>
      <%= f.text_field :cellphone, :placeholder => "010-0000-0000", :class => "form_3" %>
      <div style="float:left; display:block; width:700px; height:90px;"><br />
        <%= f.radio_button(:answer_1, 1, :style => "position:absolute; top: 234px; left: 64px;") %>
        <%= f.radio_button(:answer_1, 2, :style => "position:absolute; top: 234px; left: 155px;") %>
        <%= f.radio_button(:answer_1, 3, :style => "position:absolute; top: 234px; left: 328px;") %>
        <%= f.radio_button(:answer_1, 4, :style => "position:absolute; top: 234px; left: 511px;") %>
        <%= f.radio_button(:answer_1, 5, :style => "position:absolute; top: 257px; left: 64px;") %>
      </div>
      <div style="float:left; display:block; width:700px; height:30px; margin-top:20px;">
        <%= f.radio_button(:answer_2, 1, :style => "position:absolute; top: 322px; left: 64px;") %>
        <%= f.radio_button(:answer_2, 2, :style => "position:absolute; top: 322px; left: 290px;") %>
      </div>
      <div style="float:left; display:block; width:700px; height:110px; margin-top:50px;">
        <%= f.radio_button(:answer_3, 1, :style => "position:absolute; top: 388px; left: 64px;") %> 
        <%= f.radio_button(:answer_3, 2, :style => "position:absolute; top: 409px; left: 64px;") %>
        <%= f.radio_button(:answer_3, 3, :style => "position:absolute; top: 431px; left: 64px;") %>
        <%= f.radio_button(:answer_3, 4, :style => "position:absolute; top: 452px; left: 64px;") %>
      </div>
      <div style="float:left; display:block; width:700px; height:70px; margin-top:-10px;">
        <%= f.radio_button(:answer_4, 1, :style => "position:absolute; top: 519px; left: 64px;") %>
        <%= f.radio_button(:answer_4, 2, :style => "position:absolute; top: 518px; left: 274px;") %>
      </div>
      <div style="float:left; display:block; width:700px; height:80px; margin-top:0px;">
        <%= f.radio_button(:answer_5, 1, :style => "position:absolute; top: 585px; left: 64px;") %>
        <%= f.radio_button(:answer_5, 2, :style => "position:absolute; top: 584px; left: 274px;") %>
      </div>
      <div style="float:left; display:block; width:700px; height:50px; margin-top:-10px;">
        <%= f.radio_button(:answer_6, 1, :style => "position:absolute; top: 672px; left: 64px;") %>
        <%= f.radio_button(:answer_6, 2, :style => "position:absolute; top: 671px; left: 274px;") %>
      </div>
    </div>
      <div class="agreement">
        <input type="button" id="show_agreement" value=""><input type="checkbox" id="agreement" name="agreement" />
      </div>
      <div class="submit_btn">
        <%= f.submit "" %>
      </div>
  <% end %>
</div>

app/views/answers/new2.html.erb
<div id="main_container">
  <%= form_for @answer, :url => answers_path do |f| %>
      <%= f.text_field :company_name, :class => "form_1" %>
      <%= f.text_field :manager_name, :class => "form_2" %>
      <%= f.text_field :department, :class => "form_3" %>
      <%= f.text_field :phone, :placeholder => "02-000-0000", :class => "form_2" %>
      <%= f.text_field :work_level, :class => "form_3" %>
      <%= f.text_field :email, :placeholder => "sample@gmail.com", :class => "form_2" %>
      <%= f.text_field :cellphone, :placeholder => "010-0000-0000", :class => "form_3" %>
      <div style="float:left; display:block; width:700px; height:90px;"><br />
        <%= f.radio_button(:answer_1, 1, :style => "margin-left:45px; margin-top:40px;") %>
        <%= f.radio_button(:answer_1, 2, :style => "margin-left:65px;") %>
        <%= f.radio_button(:answer_1, 3, :style => "margin-left:155px;") %>
        <%= f.radio_button(:answer_1, 4, :style => "margin-left:165px;") %><br />
        <%= f.radio_button(:answer_1, 5, :style => "margin-left:45px; margin-top:6px;") %>
      </div>
      <div style="float:left; display:block; width:700px; height:30px; margin-top:20px;"><br>
        <%= f.radio_button(:answer_2, 1, :style => "margin-left:42px; margin-top:18px;") %>
        <%= f.radio_button(:answer_2, 2, :style => "margin-left:205px;") %>
      </div>
      <div style="float:left; display:block; width:700px; height:110px; margin-top:50px;"><br>
        <%= f.radio_button(:answer_3, 1, :style => "margin-left:42px;") %> <br />
        <%= f.radio_button(:answer_3, 2, :style => "margin-left:42px; margin-top:5px;") %><br />
        <%= f.radio_button(:answer_3, 3, :style => "margin-left:42px; margin-top:6px;") %><br />
        <%= f.radio_button(:answer_3, 4, :style => "margin-left:42px; margin-top:7px;") %>
      </div>
      <div style="float:left; display:block; width:700px; height:70px; margin-top:-10px;"><br>
        <%= f.radio_button(:answer_4, 1, :style => "margin-left:42px; margin-top:34px;") %>
        <%= f.radio_button(:answer_4, 2, :style => "margin-left:190px;") %>
      </div>
      <div style="float:left; display:block; width:700px; height:80px; margin-top:0px;"><br>
        <%= f.radio_button(:answer_5, 1, :style => "margin-left:42px; margin-top:31px;") %>
        <%= f.radio_button(:answer_5, 2, :style => "margin-left:190px;") %>
      </div>
      <div style="float:left; display:block; width:700px; height:50px; margin-top:-10px;"><br>
        <%= f.radio_button(:answer_6, 1, :style => "margin-left:42px; margin-top:48px;") %>
        <%= f.radio_button(:answer_6, 2, :style => "margin-left:190px;") %>
      </div>
    </div>
      <div class="agreement">
        <input type="button" id="show_agreement" value=""><input type="checkbox" id="agreement" name="agreement" />
      </div>
      <div class="submit_btn">
        <%= f.submit "" %>
      </div>
  <% end %>
</div>

app/views/answers/show.html.erb
<%= @answer.manager_name %>님 참여해 주셔서 감사합니다.

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Paloalto" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Paloalto</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "전체보기", "/admins/index"  %></li>
              <li><%= link_to "질문으로 모아보기", "/admins/index/question"  %></li>
              <li><%= link_to "Excel", admins_index_path(format: "xls")  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
        <%= bootstrap_flash %>
        <%= yield %>

      <footer>
      </footer>
    </div> <!-- /container -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Paloalto" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "bootstrap_and_overrides", :media => "all" %>
    <%= stylesheet_link_tag "admins", :media => "all" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Paloalto</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "전체보기", "/admins/index"  %></li>
              <li><%= link_to "질문으로 모아보기", "/admins/index/question"  %></li>
              <li><%= link_to "Excel", admins_index_path(format: "xls")  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span16">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
      </footer>
    </div> <!-- /container -->
    <%= javascript_include_tag "admins" %>

  </body>
</html>